---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: '12'
  deprecations_as_errors: true
  client_rb:
    chef_license: accept
  data_path: test/shared

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[smoke]
    attributes:
  - name: ipv6_default
    run_list:
      - recipe[smoke::ipv6_default]
    attributes:
  - name: list_of_tables
    run_list:
      - recipe[smoke::tables]
    attributes:
  - name: ipv6_list_of_tables
    run_list:
      - recipe[smoke::ipv6_tables]
    attributes:
