---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[smoke]
    attributes:
  - name: template
    run_list:
      - recipe[smoke::template]
    attributes:
